import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

/// Curated Lucide icons for inventory categories. [key] values are stored in `inventory_categories.icon`.
class InventoryCategoryLucideIcons {
  InventoryCategoryLucideIcons._();

  static final List<({String key, IconData icon})> pickerEntries = [
    (key: 'package', icon: LucideIcons.package),
    (key: 'tag', icon: LucideIcons.tag),
    (key: 'home', icon: LucideIcons.home),
    (key: 'utensils', icon: LucideIcons.utensils),
    (key: 'bath', icon: LucideIcons.bath),
    (key: 'bed', icon: LucideIcons.bed),
    (key: 'sofa', icon: LucideIcons.sofa),
    (key: 'brushCleaning', icon: LucideIcons.brushCleaning),
    (key: 'apple', icon: LucideIcons.apple),
    (key: 'carrot', icon: LucideIcons.carrot),
    (key: 'milk', icon: LucideIcons.milk),
    (key: 'refrigerator', icon: LucideIcons.refrigerator),
    (key: 'wine', icon: LucideIcons.wine),
    (key: 'pill', icon: LucideIcons.pill),
    (key: 'cross', icon: LucideIcons.cross),
    (key: 'baby', icon: LucideIcons.baby),
    (key: 'shirt', icon: LucideIcons.shirt),
    (key: 'footprints', icon: LucideIcons.footprints),
    (key: 'watch', icon: LucideIcons.watch),
    (key: 'backpack', icon: LucideIcons.backpack),
    (key: 'hammer', icon: LucideIcons.hammer),
    (key: 'wrench', icon: LucideIcons.wrench),
    (key: 'paintbrush', icon: LucideIcons.paintbrush),
    (key: 'lamp', icon: LucideIcons.lamp),
    (key: 'lightbulb', icon: LucideIcons.lightbulb),
    (key: 'fan', icon: LucideIcons.fan),
    (key: 'flower', icon: LucideIcons.flower),
    (key: 'treePine', icon: LucideIcons.treePine),
    (key: 'leaf', icon: LucideIcons.leaf),
    (key: 'dog', icon: LucideIcons.dog),
    (key: 'cat', icon: LucideIcons.cat),
    (key: 'fish', icon: LucideIcons.fish),
    (key: 'bird', icon: LucideIcons.bird),
    (key: 'book', icon: LucideIcons.book),
    (key: 'notebook', icon: LucideIcons.notebook),
    (key: 'gamepad2', icon: LucideIcons.gamepad2),
    (key: 'music', icon: LucideIcons.music),
    (key: 'headphones', icon: LucideIcons.headphones),
    (key: 'camera', icon: LucideIcons.camera),
    (key: 'smartphone', icon: LucideIcons.smartphone),
    (key: 'laptop', icon: LucideIcons.laptop),
    (key: 'monitor', icon: LucideIcons.monitor),
    (key: 'tv', icon: LucideIcons.tv),
    (key: 'router', icon: LucideIcons.router),
    (key: 'plug', icon: LucideIcons.plug),
    (key: 'battery', icon: LucideIcons.battery),
    (key: 'box', icon: LucideIcons.box),
    (key: 'archive', icon: LucideIcons.archive),
    (key: 'layers', icon: LucideIcons.layers),
    (key: 'warehouse', icon: LucideIcons.warehouse),
    (key: 'store', icon: LucideIcons.store),
    (key: 'shoppingCart', icon: LucideIcons.shoppingCart),
    (key: 'creditCard', icon: LucideIcons.creditCard),
    (key: 'key', icon: LucideIcons.key),
    (key: 'lock', icon: LucideIcons.lock),
    (key: 'umbrella', icon: LucideIcons.umbrella),
    (key: 'sun', icon: LucideIcons.sun),
    (key: 'moon', icon: LucideIcons.moon),
    (key: 'cloud', icon: LucideIcons.cloud),
    (key: 'flame', icon: LucideIcons.flame),
    (key: 'droplets', icon: LucideIcons.droplets),
    (key: 'sparkles', icon: LucideIcons.sparkles),
    (key: 'heart', icon: LucideIcons.heart),
    (key: 'star', icon: LucideIcons.star),
    (key: 'gift', icon: LucideIcons.gift),
    (key: 'partyPopper', icon: LucideIcons.partyPopper),
    (key: 'luggage', icon: LucideIcons.luggage),
    (key: 'mapPin', icon: LucideIcons.mapPin),
    (key: 'car', icon: LucideIcons.car),
    (key: 'bike', icon: LucideIcons.bike),
    (key: 'bus', icon: LucideIcons.bus),
    (key: 'plane', icon: LucideIcons.plane),
    (key: 'ship', icon: LucideIcons.ship),
    (key: 'anchor', icon: LucideIcons.anchor),
    (key: 'dumbbell', icon: LucideIcons.dumbbell),
    (key: 'trophy', icon: LucideIcons.trophy),
    (key: 'medal', icon: LucideIcons.medal),
    (key: 'paintBucket', icon: LucideIcons.paintBucket),
    (key: 'scissors', icon: LucideIcons.scissors),
    (key: 'cupSoda', icon: LucideIcons.cupSoda),
    (key: 'coffee', icon: LucideIcons.coffee),
    (key: 'microwave', icon: LucideIcons.microwave),
    (key: 'washingMachine', icon: LucideIcons.washingMachine),
  ];

  static final Map<String, IconData> _byKey = {
    // Legacy keys from older app builds
    'kitchen': LucideIcons.utensils,
    'toilet': LucideIcons.bath,
    'bedroom': LucideIcons.bed,
    'living_room': LucideIcons.sofa,
    'cleaning': LucideIcons.brushCleaning,
    'others': LucideIcons.tag,
    for (final e in pickerEntries) e.key: e.icon,
  };

  static IconData resolve(String? iconKey) {
    if (iconKey == null || iconKey.isEmpty) return LucideIcons.tag;
    return _byKey[iconKey] ?? LucideIcons.tag;
  }
}
